-- MySQL Script generated by MySQL Workbench
-- Sáb 16 Ago 2014 01:32:19 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema foobar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foobar` DEFAULT CHARACTER SET latin1 ;
USE `foobar` ;

-- -----------------------------------------------------
-- Table `foobar`.`credit_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foobar`.`credit_cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(16) NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `validity` DATETIME NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `limit` DOUBLE NOT NULL,
  `is_active` TINYINT(4) NOT NULL,
  `due_account` DATETIME NOT NULL,
  `closing` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `foobar`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foobar`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credit_card_id` INT(11) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_credit_cards_idx` (`credit_card_id` ASC),
  CONSTRAINT `fk_transactions_credit_cards`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `foobar`.`credit_cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foobar`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foobar`.`invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credit_card_id` INT(11) NOT NULL,
  `is_closed` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_credit_cards1_idx` (`credit_card_id` ASC),
  CONSTRAINT `fk_invoice_credit_cards1`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `foobar`.`credit_cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foobar`.`invoice_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foobar`.`invoice_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_transactions_invoice1_idx` (`invoice_id` ASC),
  INDEX `fk_invoice_transactions_transactions1_idx` (`transaction_id` ASC),
  CONSTRAINT `fk_invoice_transactions_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `foobar`.`invoices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_transactions_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `foobar`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
